### ISSUE TITLE
Concrete code examples

### ISSUE THREAD

**Issue by vmureithi** [mutiadavid/MpesaSDK.NET#8]
Beautiful Library but misses code examples E.g.

                var result = await mpesaclient.STKPushAsync("44444", "254722600601", 10, "passkey", "https://urdomain.ext/path", accountReference: "1234567890", transactionDesc: "Goods payment");

**Comment by mutiadavid** [comment]
Hello,

I haven't had enough time to document, I will work on it once I get time. 
You welcome to contribute and update the repo by creating a pull request.

**Comment by vmureithi** [comment]
Hi,

Getting the below error for b2c

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Tool_mpesasdk.net_b2c.Program.Main(String[] args) in C:\Users\P50\source\repos\Tool-mpesasdk.net-b2c\Tool-mpesasdk.net-b2c\Program.cs:line 21

Inner Exception 1:
CryptographicException: Bad Length.


This seems to be a credential issue…. I’m generating as follows:

string credential = "pass".ToMpesaSecurityCredential();

var result = await mpesaclient.B2CAsync("vmureithi", credential,…….);

can you help?

**Comment by mutiadavid** [comment]
Docs updated.
